### ISSUE TITLE
我觉得你格式有问题

### ISSUE THREAD

**Issue by ZStar01** [StickInsect2/blog#2]
你完全可以使用markdown的语法来进行相关的博客的书写

**Comment by ZStar01** [comment]
> 
> 
> 你完全可以使用markdown的语法来进行相关的博客的书写

顶楼上,我觉得说的很对

**Comment by ZStar01** [comment]
> 
> 
> 你完全可以使用markdown的语法来进行相关的博客的书写

我觉得说的像个狗屎一样,我就要用记事本来写,你们咬我啊

**Comment by ZStar01** [comment]
> 
> 
> > 你完全可以使用markdown的语法来进行相关的博客的书写
> 
> 我觉得说的像个狗屎一样,我就要用记事本来写,你们咬我啊

你怕不是失了智哦,狗比

**Comment by ZStar01** [comment]
> 
> 
> > > 你完全可以使用markdown的语法来进行相关的博客的书写
> > 
> > 
> > 我觉得说的像个狗屎一样,我就要用记事本来写,你们咬我啊
> 
> 你怕不是失了智哦,狗比

顶,就该喷死这些键盘侠,一天天diao本事没有就知道bb

**Comment by StickInsect2** [comment]
吊本事没有，吹牛逼最nice

**Comment by StickInsect2** [comment]
> > > 你完全可以使用markdown的语法来进行相关的博客的书写
> > 
> > 
> > 我觉得说的像个狗屎一样,我就要用记事本来写,你们咬我啊
> 
> 你怕不是失了智哦,狗比

吊本事没有，吹牛逼最nice
